languageCode = "ua-en"
theme = "terminal"
title = "SHUM"
baseURL = "/"
summaryLength = 50

[params]
showMenuItems = 8
showLanguageSelector = true
fullWidthTheme = false
centerTheme = false
autoCover = true
  showLastUpdated = false
  contentTypeName = "post"
  privatePassword = "shum2024"  # Пароль для приватного раздела

[markup]

[markup.highlight]
noClasses = false

[pagination]
pagerSize = 5

[languages]

[languages.ua]
languageName = "Ukrainian"
title = "SHUM"
weight = 1
contentDir = "content/ua"

[languages.ua.params]
minuteReadingTime = "хв на читання"
newerPosts = "Новіші статті"
copyright = ""
words = "слів"
keywords = ""
readMore = "Читати далі"
owner = ""
missingContentMessage = "Сторінку не знайдено..."
menuMore = "Показати більше"
missingBackButtonLabel = "Повернутися на головну"
subtitle = "SHUM"
readOtherPosts = "Читати інші статті"
olderPosts = "Старіші статті"
dateFormat = "02.01.2006"

[languages.ua.params.logo]
logoText = "SHUM"
logoHomeLink = "/ua"

[languages.ua.menu]

[[languages.ua.menu.main]]
identifier = "about"
name = "Про нас"
url = "/ua/"
weight = 10

[[languages.ua.menu.main]]
identifier = "posts"
name = "Блог"
url = "/ua/posts/"
weight = 20

[[languages.ua.menu.main]]
identifier = "contact"
name = "Контакти"
url = "/ua/contact/"
weight = 30

[[languages.ua.menu.main]]
identifier = "donats"
name = "Донати"
url = "https://donate.shum-ng.org/"
weight = 40
[languages.ua.menu.main.params]
NewTab = true

[[languages.ua.menu.main]]
identifier = "tools"
name = "Інструменти"
url = "/ua/tools"
weight = 50

# Добавлен новый пункт меню Матеріали
[[languages.ua.menu.main]]
identifier = "materials"
name = "Матеріали"
url = "/ua/materials/"
weight = 55

[[languages.ua.menu.main]]
identifier = "publications"
name = "Публікації"
url = "/ua/publications/"
weight = 57

[[languages.ua.menu.main]]
identifier = "vacancies"
name = "Вакансії"
url = "/ua/vacancies/"
weight = 58

[languages.en]
languageName = "English"
title = "SHUM"
weight = 2
contentDir = "content/en"

[languages.en.params]
minuteReadingTime = "min read"
newerPosts = "Newer posts"
copyright = ""
words = "words"
keywords = ""
readMore = "Read more"
owner = ""
missingContentMessage = "Page not found..."
menuMore = "Show more"
missingBackButtonLabel = "Back to home page"
subtitle = "SHUM"
readOtherPosts = "Read other posts"
olderPosts = "Older posts"
dateFormat = "02.01.2006"

[languages.en.params.logo]
logoText = "SHUM"
logoHomeLink = "/en"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 30

[[languages.en.menu.main]]
identifier = "donats"
name = "Donations"
url = "https://donate.shum-ng.org/"
weight = 40
[languages.en.menu.main.params]
NewTab = true

[[languages.en.menu.main]]
identifier = "tools"
name = "Tools"
url = "/tools/"
weight = 50

# Добавлен новый пункт меню Materials
[[languages.en.menu.main]]
identifier = "materials"
name = "Materials"
url = "/materials/"
weight = 55

[[languages.en.menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 57

[[languages.en.menu.main]]
identifier = "vacancies"
name = "Vacancies"
url = "/vacancies/"
weight = 58
